Moved some methods of testBase to @BeforeAll
autotests-cloud/qa_guru_first_course pull request #17
Opened 2020-07-12 19:46 UTC by cheshi-mantu

SelenideLogger moved to @BeforeAll
timeout to @BeforeAll
fastSetValue to @BeforeAll

2020-07-13 19:58 UTC, cheshi-mantu commented
@svasenkov 
build.gradle added task for qemoqa_tests
DemoQaElements added with tests for Text Box on elements page
DriverHelper is added
Environment is updated with qemoqaUrl
RandomUtils added to support text box tests
TestBase @BeforeAll updated to public static

2020-08-25 20:34 UTC, svasenkov commented on src/test/java/tests/DemoQaElements.java
> +        "text box" +
в аллюре это в итоге в одну строку склеится

2020-08-25 20:34 UTC, svasenkov commented on src/test/java/tests/DemoQaElements.java
> +class DemoQaElements extends TestBase {
DemoQaElementsTests

2020-08-25 20:35 UTC, svasenkov commented on src/test/java/tests/DemoQaElements.java
> +        step ("PREP: Open main page and proceed to /elements", () -> {
PREP: - неклассический вариант. 
Лучше уже GIVEN WHEN THEN или вообще ничего

2020-08-25 20:37 UTC, svasenkov requested changes

2020-08-25 20:37 UTC, svasenkov commented on src/test/java/tests/DemoQaElements.java
> +    }
Перенос на новую строку еще один не помешает

2020-08-25 20:37 UTC, svasenkov commented on src/test/java/tests/TestBase.java
>          Configuration.startMaximized=true;
Configuration.startMaximized=true; и Configuration.browser = CustomWebDriver.class.getName(); тоже можно убрать в BeforeAll

2022-05-16 07:17 UTC, closed without merging